[package]
name = "quicli"
version = "0.1.1"
description = "Quickly build cool CLI apps in Rust."
authors = ["Pascal Hertleif <killercup@gmail.com>"]
readme = "Readme.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/killercup/quicli"
categories = ["command-line-interface"]
keywords = ["cli", "prelude"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
serde = "1.0.27"
serde_derive = "1.0.27"
structopt = "0.1.6"
structopt-derive = "0.1.6"
log = "0.4.1"
env_logger = "0.5.3"
glob = "0.2.11"
rayon = "0.9.0"

[dev-dependencies]
reqwest = "0.8.3"
