title: quicli
description: Quickly build cool CLI apps in Rust.

remote_theme: killercup/jekyll-theme-rustguides
header:
  nav:
    "Source on Github": https://github.com/killercup/quicli
    "API docs": https://docs.rs/quicli
colors:
  brand: "#3e5aa5"
sass:
  style: compressed

markdown: CommonMark
plugins:
- jekyll-readme-index
- jekyll-optional-front-matter
